# Generated by Django 4.2.3 on 2023-07-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(default='86b0d1f', max_length=10, unique=True),
        ),
    ]
