# Generated by Django 4.2.3 on 2023-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_group_group_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
