# Generated by Django 4.2.3 on 2023-07-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('assignment', '0004_alter_group_group_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_admin', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_member', to='account.userprofile'),
        ),
    ]
