# Generated by Django 4.2.3 on 2023-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
